import AsyncStorage from '@react-native-async-storage/async-storage';
import apiClient, { setApiBaseUrl } from '../apiClient';

export const loginService = {
    authenticate: async (url: string, email: string, password: string) => {
        try {
            console.log('Authenticating with URL:', url);

            const response = await apiClient.post('/api/service_user/authenticate', {
                jsonrpc: "2.0",
                params: {
                    email,
                    password,
                    url
                }
            });

            // console.log('Login Response:', response.data);

            if (response.data.error) {
                return { success: false, message: response.data.error.data.message || 'Odoo Server Error' };
            }

            const result = response.data.result;

            if (result && result.success) {
                // console.log('Login Success:', result.data);
                
                return { success: true, data: result.data };
            } else {
                return { success: false, message: result?.message || 'Invalid credentials' };
            }

        } catch (error: any) {
            if (error.status !== 0) {
                console.error('Login Service Error:', error);
            }
            return {
                success: false,
                message: error.message || 'Connection failed.'
            };
        }
    },

    checkHealth: async (url: string) => {
        try {
            console.log('Checking health for URL:', url);
            const response = await apiClient.post('/api/service_user/health_check', {
                jsonrpc: "2.0",
                params: {}
            });
            return { success: true, data: response.data };
        } catch (error: any) {
            console.error('Health Check Error:', error);
            return { success: false, message: error.message };
        }
    },

    provisionToken: async (tenantUrl: string, db: string, login: string, password: string, accessToken: string, email: string) => {
        try {
            console.log('Provisioning token to tenant:', tenantUrl, 'for email:', email);
            setApiBaseUrl(tenantUrl);

            // 1. First establish Odoo Session on the tenant server
            console.log('Establishing Odoo session for database:', db);
            const authResponse = await apiClient.post('/web/session/authenticate', {
                jsonrpc: "2.0",
                method: "call",
                params: {
                    db: db.trim(),
                    login: login.trim(),
                    password: password
                }
            });

            if (authResponse.data.error) {
                const errorMsg = authResponse.data.error.data?.message || authResponse.data.error.message || 'Odoo Authentication Failed';
                throw new Error(errorMsg);
            }

            // Extract session_id from Set-Cookie header
            let sessionId = '';
            const setCookieHeaders = authResponse.headers['set-cookie'];
            if (setCookieHeaders) {
                for (const cookie of setCookieHeaders) {
                    if (cookie.includes('session_id=')) {
                        const match = cookie.match(/session_id=([^;]+)/);
                        if (match) {
                            sessionId = match[1];
                            break;
                        }
                    }
                }
            }

            if (!sessionId) {
                throw new Error('Failed to retrieve session ID from Odoo cookies');
            }

            console.log('Odoo Session established:', sessionId);
            
            await AsyncStorage.setItem('odoo_session_id', sessionId);

            // 2. Call the custom login endpoint to provision token (now with session cookie)
            const response = await apiClient.post('/api/mobile/login', {
                db,
                login,
                password,
                access_token: accessToken,
                email: email
            }, {
                headers: {
                    'Cookie': `session_id=${sessionId}`
                }
            });

            // console.log('Provisioning Response:', response.data);
            return { 
                success: response.data.success,
                access_token: response.data.access_token // Return the token (may be generated by tenant)
            };
        } catch (error: any) {
            console.error('Provisioning Error:', error);
            return { success: false, message: error.message };
        }
    }
};
